language: python

matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          sudo: required
          python: 2.7
        - os: linux
          sudo: required
          python: 3.4
        - os: linux
          sudo: required
          python: 3.6
        # Use generic language for osx
        - os: osx
          language: generic
          
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install pytest; fi

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
