[tool.poetry]
name = "pyelan"
version = "0.1.2"
description = ""
authors = ["Jonathan Keane <jkeane@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
